### ISSUE TITLE
Why did licence change?

### ISSUE THREAD

**Issue by joakimeriksson** [franckverrot/tweetnacl#1]
The tweetnacl original code is not GPL why did this piece of code end up being GPL when it is only basically linking original code into Ruby? Why not keep the more unrestricted license?

**Comment by franckverrot** [comment]
Hi @joakimeriksson and thanks for your question.

I've been creating this native extension to scratch my own itch and spent a few days working on it. In the process I made sure anybody could use it, for free, assuming a very simple constraint: if you make money out of it you'll either have to also adopt the GPL or ask the author (me) for a commercial license (which would not be covered by the GPL so one can then sell it to anybody, at any price).

I am not paying rent/food from OSS work (and don't intend to... yet? :-)), but I dedicate a significant amount of time ensuring anybody can use my products and most of the time, use it for free. So I'm expecting anyone who uses some free projects to be mindful about other people's work.

Thanks again!

**Comment by joakimeriksson** [comment]
Ok. Then you should probably tell everyone that, which is what you just did ;-)

**Comment by franckverrot** [comment]
I might be wrong on that  but you can't really GPL something "by mistake." I'm assuming anyone using it for their projects think the same way I do and that's the reason why they use it.

 I could state the license mismatch from the original license of the underlying C Lin but GPL being the most restrictive one, this is probably not required.

Thanks again,
Franck
