### ISSUE TITLE
FFI vs mkmf

### ISSUE THREAD

**Issue by SampsonCrowley** [franckverrot/tweetnacl#2]
Is there any particular reason you've chosen to use the old mkmf style of compiling instead of FFI?

Curious because I was starting to build my own extension for tweetnacl as a learning exercise and thought FFI was the standard now for Ruby => C interop

**Comment by franckverrot** [comment]
Hi!  So it’s been a while but I think I couldn’t find a tweetnacl binary/library for both OSX and Linux so I decided to vendor the code into this gem and compile it.  I do agree though: FFI is way more portable because this gem probably doesn’t work with other implementations of Ruby...  HTH!
